name: Kirkwood Pulse (Daily)

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate daily Pulse
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TZ: America/Chicago
        run: |
          python scripts/fetch_pulse.py

      - name: Commit & push (if changes)
        run: |
          git config user.name "Pulse Bot"
          git config user.email "pulsebot@users.noreply.github.com"
          git add -A
          git diff --quiet && echo "No changes" || git commit -m "Daily Pulse update"
          git push
