name: Validate Content

on:
  pull_request:
    paths:
      - "content/**"
      - "lib/content.ts"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Validate content front-matter
        run: npm run index -- --dry-run
